name: deploy AC website

on: 
  push:
    branches: [main]

jobs:
  thayam:
    runs-on: ubuntu-latest
    timeout-minutes: 5 
    steps:
     - uses: actions/checkout@v3
     - name: setup Node.js 14 
       uses: actions/setup-node@v3
       with:
         node-version: 14
     - name: Install NPM packages
       run: npm ci
     - name: Build package
       run: npm run build
       env:
         CI: false
     - name: Init new repo in dist folder and commit generated files
       run: |
         cd build
         echo > .nojekyll
         echo 'district80ac2025.com' > CNAME
         git init
         git add -A
         git config --local user.email "action@github.com"
         git config --local user.name "GitHub Action"
         git commit -m 'deploy'
     - name: Force push to destination branch
       uses: ad-m/github-push-action@master
       with:
         branch: gh-pages
         force: true
         directory: build